# -*- coding: utf-8 -*-
"""
Created on Tue Jul 13 08:46:15 2021

@author: titli
"""

region_dict = {
'Region1_Boston':['Connecticut','Maine','Massachusetts','New Hampshire','RhodeIsland','Vermont'],
'Region2_NewYork':['New Jersey','New York'],
'Region3_Philadelphia':['Delaware','DistrictofColumbia','Maryland','Pennsylvania','Virginia','WestVirginia'],
'Region4_Atlanta':['Alabama','Florida','Georgia','Kentucky','Mississippi','NorthCarolina','SouthCarolina','Tennessee'],
'Region5_Chicago':['Illinois','Indiana','Michigan','Minnesota','Ohio','Wisconsin'],
'Region6_Dallas':['Arkansas','Louisiana','NewMexico','Oklahoma','Texas'],
'Region7_KansasCity':['Iowa','Kansas','Missouri','Nebraska'],
'Region8_Denver':['Colorado','Montana','NorthDakota','SouthDakota','Utah','Wyoming'],
'Region9_SanFrancisco':['Arizona','California','Hawaii','Nevada'],
'Region10_Seattle':['Alaska','Idaho','Oregon','Washington'],
}

state_region_dict={
 'Connecticut': 'Region1_Boston',
 'Maine': 'Region1_Boston',
 'Massachusetts': 'Region1_Boston',
 'New Hampshire': 'Region1_Boston',
 'Rhode Island': 'Region1_Boston',
 'Vermont': 'Region1_Boston',
 'New Jersey': 'Region2_NewYork',
 'New York': 'Region2_NewYork',
 'Delaware': 'Region3_Philadelphia',
 'DistrictofColumbia': 'Region3_Philadelphia',
 'Maryland': 'Region3_Philadelphia',
 'Pennsylvania': 'Region3_Philadelphia',
 'Virginia': 'Region3_Philadelphia',
 'West Virginia': 'Region3_Philadelphia',
 'Alabama': 'Region4_Atlanta',
 'Florida': 'Region4_Atlanta',
 'Georgia': 'Region4_Atlanta',
 'Kentucky': 'Region4_Atlanta',
 'Mississippi': 'Region4_Atlanta',
 'North Carolina': 'Region4_Atlanta',
 'South Carolina': 'Region4_Atlanta',
 'Tennessee': 'Region4_Atlanta',
 'Illinois': 'Region5_Chicago',
 'Indiana': 'Region5_Chicago',
 'Michigan': 'Region5_Chicago',
 'Minnesota': 'Region5_Chicago',
 'Ohio': 'Region5_Chicago',
 'Wisconsin': 'Region5_Chicago',
 'Arkansas': 'Region6_Dallas',
 'Louisiana': 'Region6_Dallas',
 'New Mexico': 'Region6_Dallas',
 'Oklahoma': 'Region6_Dallas',
 'Texas': 'Region6_Dallas',
 'Iowa': 'Region7_KansasCity',
 'Kansas': 'Region7_KansasCity',
 'Missouri': 'Region7_KansasCity',
 'Nebraska': 'Region7_KansasCity',
 'Colorado': 'Region8_Denver',
 'Montana': 'Region8_Denver',
 'North Dakota': 'Region8_Denver',
 'South Dakota': 'Region8_Denver',
 'Utah': 'Region8_Denver',
 'Wyoming': 'Region8_Denver',
 'Arizona': 'Region9_SanFrancisco',
 'California': 'Region9_SanFrancisco',
 'Hawaii': 'Region9_SanFrancisco',
 'Nevada': 'Region9_SanFrancisco',
 'Alaska': 'Region10_Seattle',
 'Idaho': 'Region10_Seattle',
 'Oregon': 'Region10_Seattle',
 'Washington': 'Region10_Seattle',
}